<a href="https://colab.research.google.com/github/Tridung2k3/ThucHanhToanCC/blob/main/%C4%90STT_Th%E1%BB%B1cH%C3%A0nh_Ch%C6%B0%C6%A1ng3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tên: Mai Hoàng Trí Dũng
### MSSV: 2174802010322

# **1. Một số phép xử lý ma trận của NumPy và Scipy**

In [32]:
from scipy import linalg # Tải gói linalg của scipy vào bộ nhớ (để sử dụng)
import numpy as np # Tải gói numpy vào sử dụng với tên gọi là np

In [33]:
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)]) # số phức
c = np.array([[ (0.5, 1.5, 10), (3,2,1) ] , [(6,5,4), (7,8,9)]]) # ma trận số thực 

In [34]:
A = np.matrix(np.random.random( (2,2) ) )
print(A)
B = np.asmatrix(b) # Chuyển b thành dạng ma trận
print(B)
C = np.mat(np.random.random( (10,5) ) )
print(C)
D = np.mat([ [4, 3], [2, 6] ])
print(D)
F = np.eye(3, k=1) # tạo ma trận đường chéo. 3 là ma trận 3x3, k=1 là đường chéo nằm phía trên đường chéo chính (k = 0).
print(F)

[[0.21352236 0.48739462]
 [0.59455663 0.25381674]]
[[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]
[[0.89955234 0.56814698 0.24598729 0.9050627  0.68242941]
 [0.38573307 0.18161981 0.943137   0.62518278 0.74143068]
 [0.41519999 0.27479434 0.9465592  0.37456459 0.8542232 ]
 [0.41900439 0.03908798 0.19355799 0.21003388 0.50642423]
 [0.82909942 0.39660862 0.55595827 0.07123526 0.27526818]
 [0.86201202 0.3969529  0.60528015 0.84658527 0.72141227]
 [0.13924768 0.55572863 0.99069328 0.69701487 0.81012869]
 [0.68805338 0.77763128 0.09014247 0.91441874 0.68640437]
 [0.38586264 0.40752707 0.91650943 0.2632288  0.17685428]
 [0.64025302 0.56868772 0.40871789 0.90705315 0.92527663]]
[[4 3]
 [2 6]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [35]:
F = np.eye(3, k=0)
print(F)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
F = np.eye(3, k=-1) 
print(F)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


## Các phép xử lý đơn giản

Xem hạng ma trận: 

In [37]:
np.linalg.matrix_rank(C)


5

In [38]:
#B = A.I không chạy được trên google colab
#print(B)
#Kết quả chạy trên visual code (KQ sẽ bị biến đổi nếu run )
#[[-1.49286732  3.39776752]
# [ 2.88703142 -2.4292582 ]]

In [39]:
#C = linalg.inv(A)  không chạy được trên google colab
#print(C) 
#Kết quả chạy trên visual code (KQ sẽ bị biến đổi nếu run )
#[[-1.49286732  3.39776752]
# [ 2.88703142 -2.4292582 ]]

In [40]:
#D = linalg.det(A) không chạy được trên google colab
#print(D)
#Kết quả chạy trên visual code (KQ sẽ bị biến đổi nếu run )
#-0.16173636546636588

In [41]:
#E = A.T không chạy được trên google colab
#print(E)
#Kết quả chạy trên visual code (KQ sẽ bị biến đổi nếu run )
#[[0.39289939 0.46693797]
# [0.54954257 0.24145093]]

In [42]:
#F = A.H không chạy được trên google colab
#print(F)
#Kết quả chạy trên visual code (KQ sẽ bị biến đổi nếu run )
#[[0.39289939 0.46693797]
# [0.54954257 0.24145093]]

## Giải các loại phương trình tuyến tính: 

In [43]:
linalg.solve(A, b)

array([[-1.07737476 -1.42100573j,  0.         +8.1894594j ,
         0.         +9.18092642j],
       [ 2.52371187+19.08805725j,  0.         +0.51573679j,
         0.         +2.13311127j]])

In [47]:
E = np.mat(a).T 
print(E)

[[1]
 [2]
 [3]]


In [46]:
linalg.lstsq(F, E)

(array([[2.],
        [3.],
        [0.]]), array([], dtype=float64), 2, array([1., 1., 0.]))

## Các hàm trên ma trận

Cộng ma trận: 

In [48]:
np.add(A, D) 

matrix([[4.21352236, 3.48739462],
        [2.59455663, 6.25381674]])

Trừ ma trận: 

In [49]:
np.subtract(A, D)

matrix([[-3.78647764, -2.51260538],
        [-1.40544337, -5.74618326]])

Chia ma trận: 

In [50]:
np.divide(A, D) 

matrix([[0.05338059, 0.16246487],
        [0.29727831, 0.04230279]])

Nhân ma trận:

In [51]:
A @ D # phiên bản Python 3.x

matrix([[1.82887867, 3.56493481],
        [2.88585998, 3.3065703 ]])

In [52]:
np.multiply(D, A) 

matrix([[0.85408942, 1.46218387],
        [1.18911326, 1.52290041]])

In [53]:
np.dot(A, D)

matrix([[1.82887867, 3.56493481],
        [2.88585998, 3.3065703 ]])

In [54]:
np.vdot(A, D) 

matrix([[0.85408942]])

Hàm lũy thừa và logarith ma trận:

In [55]:
linalg.expm(A) 

array([[1.42429074, 0.64590291],
       [0.78791566, 1.47768947]])

In [56]:
linalg.logm(A)

array([[-0.74020867+1.62954437j,  0.42029725-1.42121466j],
       [ 0.51270675-1.7336929j , -0.70546143+1.51204828j]])

# **2.3. Ma trận hội tụ ***

Ma trận phân kỳ:

In [57]:
import numpy as np


**Tính ma trận A: **

In [60]:
A = np.array([ [0,1], [1,0]]) 
print(A)

[[0 1]
 [1 0]]


In [61]:
temp = A.dot(A) # tính toan lần thứ 1
print(temp) 

[[1 0]
 [0 1]]


In [62]:
k= 6
for i in range(k-1):
 temp = temp.dot(A)
 print (temp)
 print('---')

[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---


*Tính ma trận B: *

In [63]:
B = np.array([ [0,-1], [-1,0]])
print(B)

[[ 0 -1]
 [-1  0]]


In [64]:
temp = B.dot(B) # tính toan lần thứ 1
print(temp)

[[1 0]
 [0 1]]


In [65]:
k= 5
for i in range(k-1):
 temp = temp.dot(B)
 print (temp)
 print('---')

[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---


### Ma trận hội tụ - Convergent matrix: 

In [66]:
C = np.array([ [1, 0, 0], [0, 0.5, 1], [0, 0, 0.5] ])
print(C)

[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]


In [67]:
temp = C.dot(C) # tính toan lần thứ 1
print(temp)

[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]


In [68]:
k= 1000
for i in range(k-1):
 temp = temp.dot(C)
print(temp) 

[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]


In [69]:
# Sau đó, thực hiện thêm 1 lần tích 1000 lần nữa:
k= 1000
for i in range(k-1):
 temp = temp.dot(C)
print(temp) 

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# ***2.4. Ma trận Markov ***

In [70]:
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
MM = M.dot(M) # tính M2, nghĩa là M2
print (MM)

[[0.7  0.45]
 [0.3  0.55]]


In [71]:
MM = M.dot(M) # tính M3
print (MM)

[[0.7  0.45]
 [0.3  0.55]]


In [72]:
for i in range(100): # tính các M^ khác.
 MM = MM.dot(M)
print (MM) # kết luận xu hướng của jb

[[0.6 0.6]
 [0.4 0.4]]


# ***3.2. Phân rã ma trận LU ***

In [73]:
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
P, L, U = linalg.lu(M) # lệnh lina.lu sẽ tách ma trận M thành 3 ma trận P, L và U
print (P)

[[1. 0.]
 [0. 1.]]


In [74]:
print (L)

[[1.   0.  ]
 [0.25 1.  ]]


In [75]:
print (U)

[[0.8   0.3  ]
 [0.    0.625]]


In [76]:
# Thử lại với phép nhân LU có bằng ma trận M ban đầu hay không:
L.dot(U) 

array([[0.8, 0.3],
       [0.2, 0.7]])

# ***5. Bài toán ứng dụng 2 – Bài toán loan tin ***

In [77]:
# Tính toán ma trận bậc 3:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
temp = A.dot(A) # lúc này temp = A^2
print(temp)

[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]


In [78]:
temp = temp.dot(A) # lúc này temp = A^2
print(temp) 

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]


In [79]:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
sumA = A
temp = A.dot(A)
k = 3
sumA = sumA + temp
for i in range(1, k-1):
 temp = temp.dot(A)
 sumA = sumA + temp

In [80]:
print (temp) 

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]


In [81]:
print (sumA)

[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]
