<a href="https://colab.research.google.com/github/Tridung2k3/ThucHanhToanCC/blob/main/%C4%90STT_Th%E1%BB%B1cH%C3%A0nh_Ch%C6%B0%C6%A1ng6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. Khái niệm về không gian vector và tích trong**

1.2 Tich vô hướng, trực giao và ứng dụng

In [1]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
tich = np.inner(a,b) # tích vô hướng 

In [2]:
print (tich)

32


In [3]:
np.dot(a,b) 

32

*Độ dài/chuẩn của vector:*

- Chuẩn 2:

In [5]:
import numpy as np
a = np.array([1,2,-3])
z = np.linalg.norm(a)
print(z)

3.7416573867739413


- Chuẩn 1:

In [6]:
a = np.array([1,2,-3])
A = np.linalg.norm(a,1)
print(A)

6.0


In [7]:
import math
import numpy as np
a = np.array([1,2,-3])
def chuan(v,k):
  tong = 0
  for i in range(len(v)):
    tong = tong + abs(v[i]**k)
  ketqua = math.pow(tong, 1.0/k)
  return ketqua

In [8]:
chuan(a, 1) 

6.0

In [9]:
np.linalg.norm(a,1) 

6.0

In [10]:
chuan(a, 2)

3.7416573867739413

In [11]:
np.linalg.norm(a,2)

3.7416573867739413

In [12]:
chuan(a, 3)

3.3019272488946263

In [13]:
np.linalg.norm(a,3)

3.3019272488946263

In [14]:
chuan(a, 1000)

1.0442214818467515

In [15]:
np.linalg.norm(a,1000)

/usr/local/lib/python3.7/dist-packages/numpy/linalg/linalg.py:2568: RuntimeWarning: overflow encountered in power
  absx **= ord


inf

In [16]:
from scipy import linalg
linalg.norm(a) 

3.7416573867739413

In [17]:
linalg.norm(a, 100)

3.0

In [18]:
linalg.norm(a, 1000)

/usr/local/lib/python3.7/dist-packages/numpy/linalg/linalg.py:2568: RuntimeWarning: overflow encountered in power
  absx **= ord


inf

# **2. Tổ hợp tuyến tính**

In [19]:
import numpy as np
m = 10
v1 = np.array([5,-4,3])
v2 = np.array([4,3,-2])
v3 = np.array([-4,-3,-1])
v4 = np.array([-9,8,6])
mi = np.array([2,5,2,1])
M = np.array([v1,v2,v3,v4])
MT = M.transpose() 

In [20]:
print(MT)

[[ 5  4 -4 -9]
 [-4  3 -3  8]
 [ 3 -2 -1  6]]


In [21]:
v = (1.0/m)*MT.dot(mi)
print (v)

[1.3 0.9 0. ]


# **3. Tri riêng, vector riêng của ma trận và ứng dụng**

3.1 Bài toán dẫn nhập

In [22]:
import sympy as sym
x,y = sym.symbols('x y')
xy = sym.Matrix([x,y]) # khai báo vector: (x, y)T
A = sym.Matrix([[1, -68],[1,1]])
v = sym.Matrix([0, 1])
nghiem = sym.solve([A*xy-v]) # phương trình được chuyển về 1 phía
print(sym.pretty(nghiem))

⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


3.2 Trị riêng và vector riền của ma trận

In [23]:
import sympy
x, y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2) 
A = sympy.Matrix([[2,3],[3,-6]])
phuongtrinh = sympy.Eq(sympy.det(Lambda*I-A), 0)
nghiem = sympy.solve(phuongtrinh)

In [24]:
print([sympy.N(phantu,4) for phantu in nghiem]) 

[-7.000, 3.000]


In [25]:
print (sympy.pretty(nghiem)) 

[-7, 3]


3.3 Ứng dụng của trị riêng và vector riêng

In [27]:
import numpy as np
A = np.array([[2,3],[3,-6]])
D = np.array([[-7,0],[0,3]])
P = np.array([[-1.0/3, 3],[1,1]])
from numpy import linalg
from numpy import linalg as LA
P1 = LA.inv(P) # tính giá trị nghịch đảo của P 

In [28]:
print (P1) 

[[-0.3  0.9]
 [ 0.3  0.1]]


In [29]:
A.dot(P)

array([[ 2.33333333,  9.        ],
       [-7.        ,  3.        ]])

In [30]:
P @ (D ** 1000) @ P1

array([[ 5.03503397e+18,  3.50482117e+18],
       [ 3.50482117e+18, -4.31115581e+18]])

thử tinh các giá trị lũy thừa của ma trận đường chéo:

In [31]:
print (D **2)

[[49  0]
 [ 0  9]]


# **BÀI TẬP CHƯƠNG 6**

Câu 1: [Trắc nghiệm] Trong Python 3, các câu lệnh sau đây, câu lệnh nào tính chuẩn 2 của
vector a. Với a được xác định là: 

In [32]:
import numpy as np
a = np.array([1,2,3])

In [39]:
mag = lambda x : math.sqrt(sum(i** 2 for i in x))
mag(a) 

3.7416573867739413

**Câu 1 ---> D**

Câu 2: Sinh viên hãy viết các chương trình tính toán theo các công thức:

a. Tính toán khoảng cách giữa 2 vector u và v:


In [41]:
# hai điểm
u = np.array ((2, 3, 6))
v = np.array ((5, 7, 1))

# khoảng cách giữa 2 vector
d = np.linalg.norm (abs(u-v))
# hiển thị kết quả
(d) 

7.0710678118654755

b. Tính góc S của 2 vector u và v nhập vào: 
