<a href="https://colab.research.google.com/github/Tridung2k3/ThucHanhToanCC/blob/main/%C4%90STT_Th%E1%BB%B1c_H%C3%A0nh_Ch%C6%B0%C6%A1ng_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***1. Các bài toán cơ bản về không gian vector ***

1.2.Các bài toán tính toán 


*Bài tập 1:*

In [1]:
# Câu a
import numpy as np
u = np.array([2,-1,5,0])
v = np.array([4,3,1,-1])
w = np.array([-6,2,0,3])
x = 2*u-(v+3*w)
print (x)

[ 18 -11   9  -8]


In [2]:
# Câu b
x = 0.5*(2*u-v-3*w)
print (x) 

[ 9.  -5.5  4.5 -4. ]


*Bài toán 2:*

In [3]:
from numpy import linalg
A = np.matrix([[0, -1, 3],[1, 1, 1],[4, 2, 2]])
B = np.array([-1, -2, -2])
X = np.linalg.solve(A, B)
print (X)

[ 1. -2. -1.]


*Bài toán 3:*

***Phương pháp 1:***

In [4]:
A = np.matrix([[1,0],[0,0]])
B = np.matrix([[0,0],[0,1]])
from numpy import linalg as LA

In [6]:
# LA.inv(A)
# ---> Lỗi: Singular matrix

In [8]:
# LA.inv(B)
# ---> Lỗi: Singular matrix

In [9]:
LA.inv(A+B)

matrix([[1., 0.],
        [0., 1.]])

***Phương pháp 2:***

In [11]:
LA.det(A)

0.0

In [12]:
LA.det(B) 

0.0

In [13]:
LA.det(A+B)

1.0

*Bài toán 4:*

In [14]:
import sympy as sp
x, y = sp.symbols('x y') # khai báo 2 biến x và y
A = sp.Matrix([[x, y],[y, x]]) # lưu ý: kiểu ma trận của sympy là ‘Matrix’ (viết hoa)
x1, y1 = sp.symbols('x1 y1')
A1 = sp.Matrix([[x1, y1],[y1, x1]])
x2, y2 = sp.symbols('x2 y2')
A2 = sp.Matrix([[x2, y2],[y2, x2]])
A1.T

Matrix([
[x1, y1],
[y1, x1]])

In [15]:
(A1+A2).T

Matrix([
[x1 + x2, y1 + y2],
[y1 + y2, x1 + x2]])

In [16]:
((A1+A2).T).equals(A1+A2)

True

In [17]:
c = sp.symbols('c')
print (c*A)

Matrix([[c*x, c*y], [c*y, c*x]])


In [18]:
((c*A).T).equals(c*A) 

True

*Bài toán 6:*

In [19]:
import sympy as sp
c1, c2, c3 = sp.symbols('c1 c2 c3')
sp.solve([c1-2*c3, 2*c1+c2, 3*c1+2*c2+c3], [c1, c2, c3])

{c1: 0, c2: 0, c3: 0}

*Bài toán 7:*

In [20]:
import sympy as sp
c1, c2 = sp.symbols('c1 c2')
u1, u2 = sp.symbols('u1 u2')
sp.solve([c1+c2-u1,c1-c2-u2])

{c1: u1/2 + u2/2, c2: u1/2 - u2/2}

In [21]:
u1 = 0
u2 = 0
sp.solve([c1+c2-u1,c1-c2-u2])

{c1: 0, c2: 0}

# ***2. Ánh xạ tuyến tính ***

2.2.Bài toán ứng dụng: Ma trận biến đổi (ảnh/font chữ/…) 

In [22]:
# a
import numpy as np
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([4,2])
P_caua = (P.T + vecdelta).T # lệnh này sinh viên nên tách làm từng lệnh để hiểu 
print (P_caua)

[[4 4 7 7 5 5 6 6 5 5]
 [2 7 7 6 6 5 5 4 4 2]]


In [23]:
# b
import numpy as np
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([4,-2])
matran_biendoi = np.array([[1.0, 0.0],
                          [0.0, 2.0]])
P_caub = (P.T @ matran_biendoi + vecdelta).T
print (P_caub)

[[ 4.  4.  7.  7.  5.  5.  6.  6.  5.  5.]
 [-2.  8.  8.  6.  6.  4.  4.  2.  2. -2.]]


***3. [Đọc thêm] Kiểm lý thuyết về ánh xạ tuyến tính ***

3.1.Kiểm tra một ánh xạ là ánh xạ tuyến tính 

In [25]:
import sympy as sp
from sympy import lambdify
x1, x2, x3 = sp.symbols('x1 x2 x3')
bieuthuc1 = x1 - x2 + x3
f1 = lambdify([x1, x2, x3], bieuthuc1, 'numpy')
a, b, c = sp.symbols('a b c') # khai báo thêm 3 biến a, b, c giả định X = (a, b, c)
d, e, f = sp.symbols('d e f') # khai báo thêm 3 biến d, e, f giả định Y = (e, d, f)

In [26]:
f1(a, b, c) 

a - b + c

In [27]:
f1(d, e, f)

d - e + f

In [28]:
f1(a+d, b+e, c+f)

a - b + c + d - e + f

In [29]:
f1(a,b,c) + f1(d,e,f) == f1(a+d, b+e, c+f)

True

In [30]:
(f1(a,b,c) + f1(d,e,f)).equals( f1(a+d, b+e, c+f)) 

True

In [31]:
q = sp.symbols('q')
(q*f1(a,b,c) + f1(d,e,f)).equals(f1(q*a+d, q*b+e, q*c+f).expand())

True

In [32]:
bieuthuc2 = 2*x2 + 3* x3
f2 = lambdify([x1, x2, x3], bieuthuc2, 'numpy')
(q*f2(a,b,c) + f2(d,e,f)).equals(f2(q*a+d, q*b+e, q*c+f).expand())

True

3.3.Tìm ánh xạ tuyến tính 

In [33]:
import sympy as sp
a, b = sp.symbols('a b')
x, y = sp.symbols('x y')
sp.solve([a+3*b-x, 2*a+5*b-y],[a,b])

{a: -5*x + 3*y, b: 2*x - y}

In [34]:
fu1 = np.array([1,1,2])
fu2 = np.array([4,2,1])
fu = a*fu1 + b*fu2
print (fu)

[a + 4*b a + 2*b 2*a + b]


In [35]:
fu = a.subs(a, -5*x + 3*y)*fu1 + b.subs(b, 2*x - y)*fu2 # thay giá trị tìm được ở trên vào
print (fu)

[3*x - y -x + y -8*x + 5*y]


3.4.Tìm nhân của ánh xạ tuyến tính 

In [36]:
x1, x2, x3 = sp.symbols('x1 x2 x3')
sp.solve([x1+x2-x3, 2*x1+3*x2-x3, 3*x1+5*x2-x3],[x1, x2, x3])

{x1: 2*x3, x2: -x3}

3.6. Ma trận của ánh xạ tuyến tính trong cặp cơ sở 

In [39]:
import numpy as np
import math
from scipy import linalg as LA
B = np.matrix([[1.0/math.sqrt(2), 1.0/math.sqrt(2)],
 [-1.0/math.sqrt(2),1.0/math.sqrt(2)]]) # cos(pi/4)
LA.orth(B)
array = ([[-0.70710678, 0.70710678],
 [ 0.70710678, 0.70710678]])
1.0/math.sqrt(2) 


0.7071067811865475