<a href="https://colab.research.google.com/github/Tridung2k3/ThucHanhToanCC/blob/main/%C4%90STT_Th%E1%BB%B1cH%C3%A0nh_Ch%C6%B0%C6%A1ng2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. Dẫn nhập – Một số hàm về xử lý vector với Python**

Hàm “scale” tỉ số vector bằng một giá trị thực: 


In [2]:
def scale(a, v):
 return [a*vi for vi in v]
v = [3,5,7]

In [3]:
scale(10, v)

[30, 50, 70]

Hàm lấy tổng hai vector: 

In [4]:
def sumvector(v, w):
 return [vi+wi for (vi, wi) in zip(v, w)]
v = [3,5,7]
w = [2,4,6] 

In [5]:
sumvector(v, w)

[5, 9, 13]

Hàm nhân 2 vector vô hướng:

In [8]:
def dotvector(v, w):
 return sum([vi*wi for (vi, wi) in zip(v, w)]) 

In [9]:
dotvector(v, w) 

68

Hàm tính chiều dài một vector:

In [10]:
def lenvector(v):
  return dotvector(v,v) 

In [11]:
lenvector(w)

56

# ***2. Bài toán ứng dụng 1 – Phân loại tuyến tính ***

In [12]:
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4]) 

In [13]:
scores >= 0

array([False,  True,  True, False,  True, False])

In [14]:
scores < 0

array([ True, False, False,  True, False,  True])

In [18]:
np.select([scores >=0, scores < 0],['so duong', 'so am'])

array(['so am', 'so duong', 'so duong', 'so duong', 'so am', 'so duong',
       'so duong', 'so am'], dtype='<U8')

In [16]:
scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
np.select([scores >0, scores ==0, scores < 0],['so duong', 'so 0', 'so am'])

array(['so am', 'so duong', 'so duong', 'so 0', 'so am', 'so duong',
       'so 0', 'so am'], dtype='<U8')

# **3. Thực hành xử lý ma trận**

3.1. Cơ bản về xử lý ma trận 

1

In [34]:
import numpy as np # Lệnh để nạp thư viện numpy vào bộ nhớ để xử lý
from scipy import linalg, sparse # Tải 2 thư viện linalg vầ sparse của scipy vào bộ nhớ để sử dụng

In [35]:
D = np.mat([ [3,4], [5,6] ])

In [36]:
print(D)

[[3 4]
 [5 6]]


2

In [37]:
C = np.mat(np.random.random((5,7)))

In [38]:
print(C)

[[0.13250717 0.88596736 0.15234134 0.76353453 0.92315125 0.61021963
  0.73973723]
 [0.37009929 0.65980973 0.92020234 0.47956768 0.34514609 0.31164845
  0.11742175]
 [0.72314856 0.98133998 0.88890313 0.21640865 0.9515709  0.13755993
  0.827532  ]
 [0.97625231 0.53036919 0.538269   0.29682592 0.1626664  0.02728034
  0.0290803 ]
 [0.25971707 0.50407211 0.93682327 0.30416891 0.98081919 0.31092281
  0.18443904]]


3

In [39]:
A = np.mat(np.random.random((2,2))) 

In [40]:
print(A)

[[0.89684902 0.3729023 ]
 [0.60918747 0.35770918]]


4

In [41]:
b = np.array([(1+5j, 2j, 3j),(4, 5, 6)]) 

In [42]:
B = np.asmatrix(b)

5

In [43]:
print(b)

[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [44]:
print(B)

[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [49]:
print(A.T) # Chuyển vị ma trận (đảo cột thành dòng và ngược lại)

[[0.89684902 0.60918747]
 [0.3729023  0.35770918]]


6

In [50]:
print(A.I) # Ma trận nghịch đảo

[[ 3.81989504 -3.98213886]
 [-6.50537458  9.57724682]]


7

In [51]:
linalg.inv(A)

M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]]) # Ma trận dưới từ đường chéo
M_lower = np.tril(M)

In [52]:
print(M_lower)

[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]


In [53]:
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]]) # Ma trận trên từ đường chéo
M_upper = np.triu(M) 

In [54]:
print(M_upper)

[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]


In [56]:
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]]) # Vector và ma trận đường chéo
v_diag = np.diag(M) #vector đường chéo 

In [57]:
print (v_diag)

[-1 -2 -2]


In [58]:
M_diag = np.diag(v_diag) 

In [59]:
print (M_diag)

[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


Thực hiện tính toán đơn giản trên ma trận 

In [64]:
import sympy as sp
x = sp.Symbol('x')
y = sp.Symbol('y')
z = sp.Symbol('z')

In [65]:
X = sp.solve([x*x+2-6, y-1-6, x+z-1, 2*x*x-8, z*z+4-5, y-z-8], [x, y, z])

In [66]:
print(X)

[(2, 7, -1)]


Trong Python, để kiểm tra các phần tử của 2 danh sách có giá trị bằng nhau là sử dụng từ khóa
all:

In [67]:
x = [1,2,3]
y = [1,2,3]

In [69]:
print (all ([x[i] == y[i] for i in range(len(x))]))

True


In [70]:
y = [1,2,4]

In [71]:
print (all ([x[i] == y[i] for i in range(len(x))]))

False


Với numpy, lệnh so sánh hai ma trận là: numpy.array_equal( a1, a2) với a1, a2 là 2 array/dãy
số. 

In [72]:
import numpy as np
x = np.array_equal([1,2], [1,2])
y = np.array_equal(np.array([1,2]), np.array([1,2]))

In [73]:
print(x)

True


In [74]:
print(y)

True


3.2. Các phép biến đổi sơ cấp trên ma trận

In [75]:
import numpy as np 

In [76]:
A = np.reshape(np.arange(36.0), (6,6))

In [77]:
print(A) 

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]


In [78]:
I6 = np.identity(6)

In [79]:
print(I6) 

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [80]:
print(A.size)

36


In [81]:
X = np.matrix.diagonal(A)

In [82]:
print(X)

[ 0.  7. 14. 21. 28. 35.]


Thành lập ma trận A mới bằng công thức A = A + I

In [83]:
A = A + I6

In [84]:
print(A)

[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]


Tính tích (nhân) ma trận với vector (là dạng ma trận đặc biệt): 

In [85]:
vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)

In [86]:
print(C)

[ 71. 198. 325. 452. 579. 706.]


In [87]:
D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]]) # Khai báo ma trận D 2x6

In [88]:
print(D)

[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]


In [97]:
# E = A.dot(D) --> Câu lệnh bị lỗi vì shapes (6,6) and (2,6) not aligned: 6 (dim 1) != 2 (dim 0) # Tính tích ma trận A và D : A x D
#print(E)

Xây dựng ma trận F kích thước 6x2: 

In [98]:
F = np.array([[1., 1.], [2., 0.], [3., 1.], [4., 0], [5., 1], [6., 0.]])
G = A.dot(F)

In [99]:
print(F)

[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]


In [100]:
print(G)

[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]


Tính ma trận nghịch đảo:

In [101]:
S = np.linalg.inv(A) 

In [102]:
print(S)

[[ 0.37022901 -0.45610687 -0.28244275 -0.10877863  0.0648855   0.23854962]
 [-0.44656489  0.65839695 -0.23664122 -0.13167939 -0.02671756  0.07824427]
 [-0.26335878 -0.22709924  0.80916031 -0.15458015 -0.11832061 -0.08206107]
 [-0.08015267 -0.11259542 -0.14503817  0.82251908 -0.20992366 -0.24236641]
 [ 0.10305344  0.0019084  -0.09923664 -0.20038168  0.69847328 -0.40267176]
 [ 0.28625954  0.11641221 -0.05343511 -0.22328244 -0.39312977  0.4370229 ]]


In [103]:
D = np.linalg.inv(np.linalg.inv(A)) # Lệnh này làm cho các số tăng dần

In [104]:
print(D)

[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]


# **4. Bài toán ứng dụng 2 – Tính toán dãy Fibonacci: Con đường tìm đến tỉ số vàng! ***

In [105]:
import numpy as np
A = np.array( [ [1,1], [1,0] ] )
b = np.array([1, 0])
n = 10

In [106]:
for i in range(n):
 b = A.dot(b)

In [107]:
print(b)

[89 55]


# **5. Cơ bản về hệ phương trình tuyến tính và ứng dụng minh họa ***

5.2. Bài toán ứng dụng 3 – Đếm số lượng xe vào khu vực trung tâm 

In [108]:
import sympy as sp
from sympy import Symbol

In [109]:
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')

In [110]:
from sympy import solve

In [111]:
pt1 = x4+610-450-x1
pt2 = x1+400-x2-640
pt3 = x2+600-x3
pt4 = x3-x4-520

In [112]:
nghiem = sp.solve((pt1, pt2, pt3, pt4))

In [113]:
print(nghiem)

{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}


Bài tập: Sinh viên thử bằng phương pháp nhân ma trận: 

In [117]:
# import numpy as np

# A = np.matrix([[-1,0,0,1],[1,-1,0,0],[0,1,-1,0],[0,0,1,-1]]) 
# Và tính ma trận nghịch đảo:
# A_nghichdao = np.linalg.inv(A)

#----> Không chạy được chương trình

In [ ]:
#print(A_nghichdao)